import {
  LeaderboardEntry,
  MapSuggestion,
  MerchantPinType,
  QuestDetail,
  UserProfile,
} from "./types";

const HOURS = 1000 * 60 * 60;
const DAYS = 1000 * 60 * 60 * 24;

function futureIso(offset: number) {
  return new Date(Date.now() + offset).toISOString();
}

export const demoMerchants: MerchantPinType[] = [
  {
    id: "demo-cafe-bloom",
    wallet: "6g7B1nVfD9yB4h3mK2p8QwX4JcN7sLr5TzUa9Fh2PkLm",
    name: "Cafe Bloom",
    lat: 28.6139,
    lng: 77.209,
    rewardMultiplier: 1.5,
    category: "Cafe",
    district: "Connaught Place",
    vibe: "Third-wave coffee · 500 PIKO/day budget · Slow hours 2–5PM",
    isSponsored: true,
    isTrending: true,
    distance: 120,
    totalVisits: 142,
    rewardPool: 142,
    hotspotScore: 96,
    avatar: "CX",
    quests: [
      {
        id: "quest-bloom",
        title: "Buy any drink, earn 5 PIKO",
        rewardAmount: 5,
        rewardToken: "PIKO",
        questType: "Sponsored",
        xpReward: 50,
        expiresAt: futureIso(52 * HOURS),
        claimedCount: 34,
        maxClaims: 100,
      },
    ],
  },
  {
    id: "demo-pixel-pizza",
    wallet: "7QpM4vTxD8fJ2kLmN5rS9wXaBcDeFgHiJkLmNoPqRsTu",
    name: "Pixel Pizza",
    lat: 28.6175,
    lng: 77.2065,
    rewardMultiplier: 2.1,
    category: "Restaurant",
    district: "Janpath",
    vibe: "High-demand late-night order flow",
    isSponsored: true,
    isTrending: false,
    distance: 250,
    totalVisits: 88,
    rewardPool: 110,
    hotspotScore: 82,
    avatar: "PP",
    quests: [
      {
        id: "quest-pizza-combo",
        title: "Combo Slice Sprint",
        rewardAmount: 0.7,
        rewardToken: "PIKO",
        questType: "Purchase",
        xpReward: 20,
        expiresAt: futureIso(20 * HOURS),
        claimedCount: 52,
        maxClaims: 90,
      },
      {
        id: "quest-pizza-night",
        title: "Neon Night Loyalty",
        rewardAmount: 0.35,
        rewardToken: "PIKO",
        questType: "Repeat",
        xpReward: 12,
        expiresAt: futureIso(36 * HOURS),
        claimedCount: 18,
        maxClaims: 60,
      },
    ],
  },
  {
    id: "demo-neon-threads",
    wallet: "8LmP2rStV4xY6zAbCdEfGhJkLmNoPqRsTuVwXyZaBcDe",
    name: "Neon Threads",
    lat: 28.6095,
    lng: 77.211,
    rewardMultiplier: 1.6,
    category: "Retail",
    district: "Barakhamba Road",
    vibe: "Retail activation with strong conversion",
    isSponsored: false,
    isTrending: true,
    distance: 410,
    totalVisits: 72,
    rewardPool: 64,
    hotspotScore: 74,
    avatar: "NT",
    quests: [
      {
        id: "quest-threads-drop",
        title: "Mint the Look",
        rewardAmount: 0.5,
        rewardToken: "PIKO",
        questType: "Purchase",
        xpReward: 18,
        expiresAt: futureIso(40 * HOURS),
        claimedCount: 27,
        maxClaims: 75,
      },
    ],
  },
  {
    id: "demo-arcade-orbit",
    wallet: "9NoQ4sTuV6wX8yZaBcDeFgHiJkLmNpQrStUvWxYzAbCd",
    name: "Arcade Orbit",
    lat: 28.616,
    lng: 77.212,
    rewardMultiplier: 1.8,
    category: "Entertainment",
    district: "Inner Circle",
    vibe: "Entertainment venue with repeat traffic",
    isSponsored: false,
    isTrending: true,
    distance: 320,
    totalVisits: 96,
    rewardPool: 80,
    hotspotScore: 79,
    avatar: "AO",
    quests: [
      {
        id: "quest-orbit-arcade",
        title: "Arcade Streak",
        rewardAmount: 0.6,
        rewardToken: "PIKO",
        questType: "Purchase",
        xpReward: 22,
        expiresAt: futureIso(28 * HOURS),
        claimedCount: 43,
        maxClaims: 95,
      },
    ],
  },
  {
    id: "demo-green-bowl",
    wallet: "4QrS6tUvW8xY1zAbCdEfGhJkLmNoPqRsTuVwXyZaBcDe",
    name: "Green Bowl",
    lat: 28.612,
    lng: 77.213,
    rewardMultiplier: 1.9,
    category: "Restaurant",
    district: "Hanuman Road",
    vibe: "Healthy lunch traffic spike",
    isSponsored: true,
    isTrending: true,
    distance: 560,
    totalVisits: 115,
    rewardPool: 130,
    hotspotScore: 88,
    avatar: "GB",
    quests: [
      {
        id: "quest-bowl-boost",
        title: "Clean Fuel Combo",
        rewardAmount: 0.9,
        rewardToken: "PIKO",
        questType: "Sponsored",
        xpReward: 24,
        expiresAt: futureIso(18 * HOURS),
        claimedCount: 61,
        maxClaims: 120,
      },
      {
        id: "quest-bowl-chain",
        title: "Two Stop Chain",
        rewardAmount: 0.4,
        rewardToken: "PIKO",
        questType: "Chain",
        xpReward: 15,
        expiresAt: futureIso(46 * HOURS),
        claimedCount: 13,
        maxClaims: 50,
      },
    ],
  },
  {
    id: "demo-fit-forge",
    wallet: "5StU7vWxY9zAbCdEfGhJkLmNoPqRsTuVwXyZaBcDeFgH",
    name: "Fit Forge",
    lat: 28.611,
    lng: 77.205,
    rewardMultiplier: 1.4,
    category: "Fitness",
    district: "Bengali Market",
    vibe: "Fitness studio with repeat member visits",
    isSponsored: false,
    isTrending: false,
    distance: 520,
    totalVisits: 44,
    rewardPool: 48,
    hotspotScore: 58,
    avatar: "FF",
    quests: [
      {
        id: "quest-forge-recovery",
        title: "Workout Recharge",
        rewardAmount: 0.45,
        rewardToken: "PIKO",
        questType: "Visit",
        xpReward: 16,
        expiresAt: futureIso(72 * HOURS),
        claimedCount: 21,
        maxClaims: 70,
      },
    ],
  },
  {
    id: "demo-sol-records",
    wallet: "3TuV8wXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHj",
    name: "Sol Records",
    lat: 28.618,
    lng: 77.208,
    rewardMultiplier: 1.3,
    category: "Entertainment",
    district: "Mandi House",
    vibe: "Cultural venue with repeat foot traffic",
    isSponsored: false,
    isTrending: false,
    distance: 390,
    totalVisits: 38,
    rewardPool: 34,
    hotspotScore: 49,
    avatar: "SR",
    quests: [
      {
        id: "quest-records-vinyl",
        title: "Spin Session",
        rewardAmount: 0.35,
        rewardToken: "PIKO",
        questType: "Visit",
        xpReward: 10,
        expiresAt: futureIso(65 * HOURS),
        claimedCount: 15,
        maxClaims: 80,
      },
    ],
  },
  {
    id: "demo-chai-circuit",
    wallet: "2UvW9xYzAbCdEfGhJkLmNoPqRsTuVwXyZaBcDeFgHiJk",
    name: "Chai Circuit",
    lat: 28.615,
    lng: 77.2035,
    rewardMultiplier: 2.8,
    category: "Cafe",
    district: "Baba Kharak Singh Marg",
    vibe: "Budget-rich beverage venue with high incentive headroom",
    isSponsored: false,
    isTrending: false,
    distance: 680,
    totalVisits: 210,
    rewardPool: 164,
    hotspotScore: 91,
    avatar: "CC",
    quests: [
      {
        id: "quest-chai-repeat",
        title: "Circuit Streak",
        rewardAmount: 1.2,
        rewardToken: "PIKO",
        questType: "Repeat",
        xpReward: 30,
        expiresAt: futureIso(16 * HOURS),
        claimedCount: 72,
        maxClaims: 110,
      },
    ],
  },
  {
    id: "demo-lumen-lanes",
    wallet: "1VwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkL",
    name: "Lumen Lanes",
    lat: 28.6076,
    lng: 77.2145,
    rewardMultiplier: 1.7,
    category: "Entertainment",
    district: "Tolstoy Lane",
    vibe: "Entertainment venue with group traffic",
    isSponsored: true,
    isTrending: true,
    distance: 790,
    totalVisits: 128,
    rewardPool: 98,
    hotspotScore: 86,
    avatar: "LL",
    quests: [
      {
        id: "quest-lanes-duo",
        title: "Duo Strike Bonus",
        rewardAmount: 0.65,
        rewardToken: "PIKO",
        questType: "Sponsored",
        xpReward: 21,
        expiresAt: futureIso(31 * HOURS),
        claimedCount: 48,
        maxClaims: 90,
      },
    ],
  },
];

export const demoQuests: QuestDetail[] = [
  {
    id: "quest-bloom",
    merchantId: "demo-cafe-bloom",
    title: "Buy any drink, earn 5 PIKO",
    description:
      "Cafe Bloom runs a 500 PIKO/day budget with a 1.4× slow-hour multiplier (2–5 PM). Tap the pin, pay for any drink, and watch the AI verify location + payment before settling 5 PIKO.",
    rewardAmount: 5,
    rewardToken: "PIKO",
    xpReward: 50,
    minSpend: 5,
    maxClaims: 100,
    claimedCount: 34,
    questType: "Sponsored",
    expiresAt: futureIso(52 * HOURS),
    multiplier: 1.5,
    bonusWindow: "Demo mode settles immediately after the scripted payment check.",
    badgeReward: "Cafe Bloom Proof NFT",
    claimVelocity: 68,
    merchant: {
      id: "demo-cafe-bloom",
      wallet: "6g7B1nVfD9yB4h3mK2p8QwX4JcN7sLr5TzUa9Fh2PkLm",
      name: "Cafe Bloom",
      category: "Cafe",
      lat: 28.6139,
      lng: 77.209,
      distance: 120,
      district: "Connaught Place",
      vibe: "Third-wave coffee · 500 PIKO/day budget · Slow hours 2–5PM",
    },
    requirements: [
      { id: "req-1", label: "Tap the merchant pin", done: true, hint: "Single scripted location" },
      { id: "req-2", label: "Claim the incentive flow", done: false, hint: "One tap in demo mode" },
      { id: "req-3", label: "Confirm the mock payment", done: false, hint: "Repeatable for judges" },
      { id: "req-4", label: "Let AI verify and settle 5 PIKO", done: false, hint: "Visible decision panel" },
    ],
    statusSteps: [
      { label: "Ready", state: "complete" },
      { label: "Claimed", state: "active" },
      { label: "Paying", state: "locked" },
      { label: "Rewarded", state: "locked" },
    ],
  },
  {
    id: "quest-bowl-boost",
    merchantId: "demo-green-bowl",
    title: "Clean Fuel Combo",
    description:
      "Pay with Solana Pay to trigger an instant sponsored incentive and observe live lunchtime demand shaping.",
    rewardAmount: 0.9,
    rewardToken: "PIKO",
    xpReward: 24,
    minSpend: 7,
    maxClaims: 120,
    claimedCount: 61,
    questType: "Sponsored",
    expiresAt: futureIso(18 * HOURS),
    multiplier: 1.9,
    bonusWindow: "Healthy hour multiplier active until 3:00 PM",
    badgeReward: "Clean Fuel Crest",
    claimVelocity: 73,
    merchant: {
      id: "demo-green-bowl",
      wallet: "4QrS6tUvW8xY1zAbCdEfGhJkLmNoPqRsTuVwXyZaBcDe",
      name: "Green Bowl",
      category: "Restaurant",
      lat: 28.612,
      lng: 77.213,
      distance: 560,
      district: "Hanuman Road",
      vibe: "Lunch rush sponsorship program",
    },
    requirements: [
      { id: "req-a", label: "Check in within 600m", done: true, hint: "In range" },
      { id: "req-b", label: "Purchase combo menu item", done: false, hint: "Eligible menu tagged" },
      { id: "req-c", label: "Use a connected wallet", done: false, hint: "Phantom or Backpack" },
    ],
    statusSteps: [
      { label: "Ready", state: "complete" },
      { label: "Claimed", state: "active" },
      { label: "Paying", state: "locked" },
      { label: "Rewarded", state: "locked" },
    ],
  },
  {
    id: "quest-chai-repeat",
    merchantId: "demo-chai-circuit",
    title: "Circuit Streak",
    description:
      "Come back for the premium repeat program and convert a tea purchase into the highest live multiplier in the area.",
    rewardAmount: 1.2,
    rewardToken: "PIKO",
    xpReward: 30,
    minSpend: 6,
    maxClaims: 110,
    claimedCount: 72,
    questType: "Repeat",
    expiresAt: futureIso(16 * HOURS),
    multiplier: 2.8,
    bonusWindow: "Repeat-visit streak bonus for the next 54m",
    badgeReward: "Circuit Flame Seal",
    claimVelocity: 81,
    merchant: {
      id: "demo-chai-circuit",
      wallet: "2UvW9xYzAbCdEfGhJkLmNoPqRsTuVwXyZaBcDeFgHiJk",
      name: "Chai Circuit",
      category: "Cafe",
      lat: 28.615,
      lng: 77.2035,
      distance: 680,
      district: "Baba Kharak Singh Marg",
      vibe: "Late-evening multiplier demand spike",
    },
    requirements: [
      { id: "req-r1", label: "Return visit detected", done: true, hint: "Last visit 2 days ago" },
      { id: "req-r2", label: "Spend at least $6", done: false, hint: "Tap-to-pay supported" },
      { id: "req-r3", label: "Finish before the tea window closes", done: false, hint: "16h left" },
    ],
    statusSteps: [
      { label: "Ready", state: "complete" },
      { label: "Claimed", state: "active" },
      { label: "Paying", state: "locked" },
      { label: "Rewarded", state: "locked" },
    ],
  },
];

export const demoPrimaryMerchant = demoMerchants[0];
export const demoPrimaryQuest = demoQuests[0];

export const demoAiPreview = {
  fraudScore: 8,
  fraudFlags: ["verified_payment", "world_id_verified", "clean_travel_history"],
  rewardMultiplier: 1.3,
  rewardReasons: ["First-time visit", "Verified payment", "Budget healthy"],
  decision: "APPROVED" as const,
  worldVerified: true,
};

export const demoLeaderboardByPeriod: Record<"weekly" | "monthly" | "alltime", LeaderboardEntry[]> = {
  weekly: [
    { wallet: "7N6Q...1KxP", xp: 2850, rank: 1, period: "weekly", avatar: "NK", title: "Top Operator", delta: 2, sparkline: [44, 50, 48, 60, 72, 88, 96], streak: 7 },
    { wallet: "8rV2...9LMt", xp: 2410, rank: 2, period: "weekly", avatar: "LM", title: "Growth Lead", delta: 1, sparkline: [36, 40, 42, 51, 63, 68, 84], streak: 5 },
    { wallet: "5Pkx...4vUn", xp: 1970, rank: 3, period: "weekly", avatar: "PU", title: "Program Analyst", delta: -1, sparkline: [34, 34, 39, 45, 53, 56, 64], streak: 4 },
    { wallet: "3Lzm...7QeR", xp: 1640, rank: 4, period: "weekly", avatar: "LQ", title: "Demand Builder", delta: 3, sparkline: [18, 22, 30, 31, 36, 48, 55], streak: 4 },
    { wallet: "9Bcd...2FwN", xp: 1420, rank: 5, period: "weekly", avatar: "BF", title: "Area Lead", delta: 1, sparkline: [16, 19, 22, 28, 34, 37, 42], streak: 3 },
    { wallet: "4Hjn...6TpK", xp: 1180, rank: 6, period: "weekly", avatar: "HT", title: "Rewards Lead", delta: 0, sparkline: [12, 15, 17, 24, 22, 31, 36], streak: 3 },
    { wallet: "2Wxy...8GsJ", xp: 950, rank: 7, period: "weekly", avatar: "WG", title: "Merchant Scout", delta: 2, sparkline: [8, 14, 13, 19, 21, 24, 30], streak: 2 },
    { wallet: "6Mnp...3HrV", xp: 820, rank: 8, period: "weekly", avatar: "MH", title: "Local Operator", delta: -2, sparkline: [10, 10, 12, 14, 17, 18, 20], streak: 2 },
    { wallet: "Demo...User", xp: 680, rank: 9, period: "weekly", avatar: "DU", title: "Protocol Builder", delta: 4, sparkline: [6, 8, 10, 12, 18, 24, 28], streak: 5, isCurrentUser: true },
    { wallet: "1Qrs...5DkL", xp: 540, rank: 10, period: "weekly", avatar: "QD", title: "Network Analyst", delta: 0, sparkline: [5, 6, 7, 9, 11, 12, 14], streak: 1 },
  ],
  monthly: [
    { wallet: "8rV2...9LMt", xp: 9120, rank: 1, period: "monthly", avatar: "LM", title: "Growth Lead", delta: 1, sparkline: [22, 28, 36, 45, 57, 70, 88], streak: 14 },
    { wallet: "7N6Q...1KxP", xp: 8840, rank: 2, period: "monthly", avatar: "NK", title: "Top Operator", delta: -1, sparkline: [24, 30, 35, 42, 54, 66, 80], streak: 12 },
    { wallet: "3Lzm...7QeR", xp: 7310, rank: 3, period: "monthly", avatar: "LQ", title: "Demand Builder", delta: 2, sparkline: [18, 24, 28, 34, 44, 56, 63], streak: 10 },
    { wallet: "5Pkx...4vUn", xp: 6880, rank: 4, period: "monthly", avatar: "PU", title: "Program Analyst", delta: -1, sparkline: [20, 22, 26, 30, 36, 41, 52], streak: 9 },
    { wallet: "9Bcd...2FwN", xp: 6030, rank: 5, period: "monthly", avatar: "BF", title: "Area Lead", delta: 1, sparkline: [12, 18, 22, 27, 34, 38, 46], streak: 8 },
    { wallet: "Demo...User", xp: 4210, rank: 6, period: "monthly", avatar: "DU", title: "Protocol Builder", delta: 3, sparkline: [8, 11, 15, 20, 28, 36, 44], streak: 11, isCurrentUser: true },
    { wallet: "4Hjn...6TpK", xp: 3880, rank: 7, period: "monthly", avatar: "HT", title: "Rewards Lead", delta: 0, sparkline: [10, 13, 16, 20, 24, 29, 33], streak: 7 },
    { wallet: "2Wxy...8GsJ", xp: 3410, rank: 8, period: "monthly", avatar: "WG", title: "Merchant Scout", delta: 2, sparkline: [8, 10, 12, 16, 18, 22, 28], streak: 6 },
    { wallet: "6Mnp...3HrV", xp: 3160, rank: 9, period: "monthly", avatar: "MH", title: "Local Operator", delta: -1, sparkline: [6, 9, 10, 11, 14, 18, 22], streak: 5 },
    { wallet: "1Qrs...5DkL", xp: 2890, rank: 10, period: "monthly", avatar: "QD", title: "Network Analyst", delta: 0, sparkline: [5, 7, 8, 10, 12, 15, 18], streak: 4 },
  ],
  alltime: [
    { wallet: "7N6Q...1KxP", xp: 24120, rank: 1, period: "alltime", avatar: "NK", title: "Top Operator", delta: 0, sparkline: [12, 18, 28, 42, 56, 74, 92], streak: 26 },
    { wallet: "8rV2...9LMt", xp: 22980, rank: 2, period: "alltime", avatar: "LM", title: "Growth Lead", delta: 0, sparkline: [10, 16, 24, 38, 50, 64, 88], streak: 24 },
    { wallet: "5Pkx...4vUn", xp: 18660, rank: 3, period: "alltime", avatar: "PU", title: "Program Analyst", delta: 1, sparkline: [8, 12, 18, 28, 39, 50, 68], streak: 19 },
    { wallet: "3Lzm...7QeR", xp: 17240, rank: 4, period: "alltime", avatar: "LQ", title: "Demand Builder", delta: -1, sparkline: [8, 10, 16, 24, 34, 44, 56], streak: 17 },
    { wallet: "9Bcd...2FwN", xp: 14880, rank: 5, period: "alltime", avatar: "BF", title: "Area Lead", delta: 0, sparkline: [6, 8, 12, 16, 23, 32, 40], streak: 15 },
    { wallet: "4Hjn...6TpK", xp: 13010, rank: 6, period: "alltime", avatar: "HT", title: "Rewards Lead", delta: 0, sparkline: [6, 7, 10, 14, 20, 26, 34], streak: 13 },
    { wallet: "Demo...User", xp: 11840, rank: 7, period: "alltime", avatar: "DU", title: "Protocol Builder", delta: 2, sparkline: [4, 6, 10, 15, 23, 34, 46], streak: 18, isCurrentUser: true },
    { wallet: "2Wxy...8GsJ", xp: 11040, rank: 8, period: "alltime", avatar: "WG", title: "Merchant Scout", delta: -1, sparkline: [4, 5, 8, 11, 16, 22, 30], streak: 11 },
    { wallet: "6Mnp...3HrV", xp: 10110, rank: 9, period: "alltime", avatar: "MH", title: "Local Operator", delta: 0, sparkline: [4, 5, 6, 9, 12, 18, 24], streak: 9 },
    { wallet: "1Qrs...5DkL", xp: 9400, rank: 10, period: "alltime", avatar: "QD", title: "Network Analyst", delta: 0, sparkline: [3, 4, 5, 7, 10, 14, 18], streak: 8 },
  ],
};

export const demoLeaderboard = demoLeaderboardByPeriod.weekly;

export const demoUser: UserProfile = {
  wallet: "Demo...User",
  xp: 680,
  level: 7,
  totalRewards: 18.6,
  questsCompleted: 24,
  streak: 5,
  nextLevelXp: 1400,
  solBalance: 2.84,
  pikoBalance: 18.6,
  rewardsThisWeek: 4.85,
  levelTitle: "Protocol Operator",
  badges: [
    {
      id: "badge-first-scan",
      name: "First Settlement",
      description: "Completed your first verified Pay & Earn settlement.",
      imageUrl: "/icons/icon-192.svg",
      rarity: "Rare",
      earnedAt: futureIso(-10 * DAYS),
      icon: "Scan",
    },
    {
      id: "badge-trailblazer",
      name: "Merchant Network",
      description: "Completed verified activity across 10 unique merchants.",
      imageUrl: "/icons/icon-192.svg",
      rarity: "Epic",
      earnedAt: futureIso(-8 * DAYS),
      icon: "Trail",
    },
    {
      id: "badge-streak-3",
      name: "Consistency Signal",
      description: "Maintained a 3-day verified settlement streak.",
      imageUrl: "/icons/icon-192.svg",
      rarity: "Legendary",
      earnedAt: futureIso(-3 * DAYS),
      icon: "Flame",
    },
    {
      id: "badge-sponsored",
      name: "Sponsored Flow",
      description: "Completed 5 sponsored merchant incentive flows.",
      imageUrl: "/icons/icon-192.svg",
      rarity: "Epic",
      earnedAt: futureIso(-1 * DAYS),
      icon: "Signal",
    },
    {
      id: "badge-night-run",
      name: "After-Hours Operator",
      description: "Closed 3 verified settlements after dark without breaking streak.",
      imageUrl: "/icons/icon-192.svg",
      rarity: "Rare",
      earnedAt: futureIso(-12 * HOURS),
      icon: "Night",
    },
  ],
  recentActivity: [
    {
      id: "activity-1",
      type: "reward",
      title: "Earned 0.80 PIKO",
      detail: "Cafe Bloom sponsored quest completed",
      timestamp: "2h ago",
    },
    {
      id: "activity-2",
      type: "quest",
      title: "Completed Combo Slice Program",
      detail: "+20 XP and top-10 weekly climb",
      timestamp: "5h ago",
    },
    {
      id: "activity-3",
      type: "badge",
      title: "Recorded Consistency Signal",
      detail: "Proof NFT recorded to your wallet",
      timestamp: "1d ago",
    },
    {
      id: "activity-4",
      type: "streak",
      title: "5-day streak preserved",
      detail: "Next streak multiplier adjustment at day 7",
      timestamp: "1d ago",
    },
  ],
};

export const demoSuggestions: MapSuggestion[] = [
  {
    merchantName: "Cafe Bloom",
    reasoning: "Tap the Cafe Bloom pin, confirm the payment, and watch AI settle 5 PIKO with a visible receipt.",
    confidence: 0.92,
  },
  {
    merchantName: "Green Bowl",
    reasoning: "Lunch window is heating up at Green Bowl. The sponsored quest and chain bonus can net 39 XP in one route.",
    confidence: 0.87,
  },
  {
    merchantName: "Chai Circuit",
    reasoning: "If you can travel 680m, Chai Circuit is still the highest live multiplier on the map with a premium repeat quest.",
    confidence: 0.8,
  },
];

export function getDemoQuestById(id: string) {
  return demoQuests.find((quest) => quest.id === id) ?? demoQuests[0];
}

export function getDemoLeaderboard(period: string) {
  if (period === "monthly") {
    return demoLeaderboardByPeriod.monthly;
  }

  if (period === "alltime") {
    return demoLeaderboardByPeriod.alltime;
  }

  return demoLeaderboardByPeriod.weekly;
}
